[package]
name = "jetbra"
version = "0.1.2"
edition = "2021"
authors = ["Yanchen Chen <yanchen1610@gamil.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.5", features = ["derive"] }
dirs = "5.0.1"
enum-iterator = "1.4.0"
